# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  apt_packages:
    - dos2unix
    - graphviz
  commands:
    # Create output directory
    # Install Python packages
    - pip install -e .[dev]
    # Convert line endings and make scripts executable
    - find . -type f -name "*.sh" -exec dos2unix {} \;
    - find . -type f -name "*.sh" -exec chmod +x {} \;
    # Build documentation
    # - /bin/bash -c "cd docs && rm -rf source/auto"
    # - /bin/bash -c "cd docs && sphinx-apidoc -f -o source/auto ../twin4build --maxdepth=1"
    # - /bin/bash -c "cd docs && python clean_sphinx_docs.py"
    - /bin/bash -c "cd docs && make buildapi"
    - /bin/bash -c "cd docs && make html"

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Optional but recommended, declare the Python requirements required
# to build your documentation
# python:
#   install:
#     - requirements: docs/requirements.txt
