# Makefile generated by OpenModelica
# Platform: win64

# Simulations use -O3 by default
CC=clang
CXX=clang++
LINK=clang++ -shared -Xlinker --export-all-symbols
EXEEXT=.exe
DLLEXT=.dll
CFLAGS_BASED_ON_INIT_FILE=
# define OMC_CFLAGS_OPTIMIZATION env variable to your desired optimization level to override this
OMC_CFLAGS_OPTIMIZATION=-Os
DEBUG_FLAGS=$(OMC_CFLAGS_OPTIMIZATION)
CFLAGS=$(CFLAGS_BASED_ON_INIT_FILE) $(DEBUG_FLAGS) -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse ${MODELICAUSERCFLAGS}   
CPPFLAGS="-IC:/Program Files/OpenModelica1.18.0-64bit/lib/omlibrary/Modelica 4.0.0/Resources/C-Sources" -I"C:/Program Files/OpenModelica1.18.0-64bit/include/omc/c" -I. -DOPENMODELICA_XML_FROM_FILE_AT_RUNTIME -DOMC_MODEL_PREFIX=Radiator -DOMC_NUM_MIXED_SYSTEMS=0 -DOMC_NUM_LINEAR_SYSTEMS=5 -DOMC_NUM_NONLINEAR_SYSTEMS=2 -DOMC_NDELAY_EXPRESSIONS=0 -DOMC_NVAR_STRING=0
# define OMC_LDFLAGS_LINK_TYPE env variable to "static" to override this
OMC_LDFLAGS_LINK_TYPE=dynamic
RUNTIME_LIBS= -Wl,-B$(OMC_LDFLAGS_LINK_TYPE) -lSimulationRuntimeC -Wl,-Bdynamic  -Wl,-B$(OMC_LDFLAGS_LINK_TYPE) -lomcgc -lregex -ltre -lintl -liconv -lexpat -static-libgcc -luuid -loleaut32 -lole32 -limagehlp -lws2_32 -llis -lsundials_nvecserial -lsundials_sunmatrixdense -lsundials_sunmatrixsparse -lsundials_sunlinsoldense -lsundials_sunlinsolklu -lsundials_sunlinsollapackdense -lsundials_sunlinsolspbcgs -lsundials_sunlinsolspfgmr -lsundials_sunlinsolspgmr -lsundials_sunlinsolsptfqmr -lsundials_sunnonlinsolnewton -lsundials_cvode -lsundials_cvodes -lsundials_idas -lsundials_kinsol -lumfpack -lklu -lcolamd -lbtf -lamd -lsuitesparseconfig -lipopt -lcoinmumps -lpthread -lm  -lgfortran -lquadmath -lmingw32 -lgcc_eh -lmoldname -lmingwex  -luser32 -lkernel32 -ladvapi32 -lshell32 -lopenblas -lcminpack -Wl,-Bdynamic -lwsock32  -Wl,-B$(OMC_LDFLAGS_LINK_TYPE)  -lstdc++ -Wl,-Bdynamic 
LDFLAGS=-L"C:/Program Files/OpenModelica1.18.0-64bit/lib//omc" -L"C:/Program Files/OpenModelica1.18.0-64bit/lib" -Wl,--stack,16777216,-rpath,"C:/Program Files/OpenModelica1.18.0-64bit/lib//omc" -Wl,-rpath,"C:/Program Files/OpenModelica1.18.0-64bit/lib"  -fopenmp -Wl,-Bstatic -lregex -ltre -lintl -liconv -lexpat -lomcgc -lpthread -loleaut32 -limagehlp -lhdf5 -lz -lszip -Wl,-Bdynamic $(RUNTIME_LIBS) 
DIREXTRA=-L"C:/Users/jabj/OneDrive - Syddansk Universitet/PhD_Project_Jakob/Twin4build/Modelica/FMUPreparedModels"
MAINFILE=Radiator.c
MAINOBJ=Radiator.o
CFILES=Radiator_functions.c Radiator_records.c \
Radiator_01exo.c Radiator_02nls.c Radiator_03lsy.c Radiator_04set.c Radiator_05evt.c Radiator_06inz.c Radiator_07dly.c \
Radiator_08bnd.c Radiator_09alg.c Radiator_10asr.c Radiator_11mix.c Radiator_12jac.c Radiator_13opt.c Radiator_14lnz.c \
Radiator_15syn.c Radiator_16dae.c Radiator_17inl.c Radiator_18spd.c 

OFILES=$(CFILES:.c=.o)
GENERATEDFILES=$(MAINFILE) Radiator.makefile Radiator_literals.h Radiator_functions.h $(CFILES)

.PHONY: omc_main_target clean bundle

# This is to make sure that Radiator_*.c are always compiled.
.PHONY: $(CFILES)

omc_main_target: $(MAINOBJ) Radiator_functions.h Radiator_literals.h $(OFILES)
	$(CC) -I. -o Radiator$(EXEEXT) $(MAINOBJ) $(OFILES) $(CPPFLAGS) $(DIREXTRA)  "-LC:/Program Files/OpenModelica1.18.0-64bit/lib//omc" "-LC:/Program Files/OpenModelica1.18.0-64bit/lib/" "-LC:/Users/jabj/AppData/Roaming/.openmodelica/binaries/Modelica" "-LC:/Program Files/OpenModelica1.18.0-64bit/lib/omlibrary/Modelica 4.0.0/Resources/Library/mingw64" "-LC:/Program Files/OpenModelica1.18.0-64bit/lib/omlibrary/Modelica 4.0.0/Resources/Library/win64" "-LC:/Program Files/OpenModelica1.18.0-64bit/lib/omlibrary/Modelica 4.0.0/Resources/Library" -lModelicaExternalC $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)
clean:
	@rm -f Radiator_records.o $(MAINOBJ)

bundle:
	@tar -cvf Radiator_Files.tar $(GENERATEDFILES)