/* Additional record code for Radiator generated by the OpenModelica Compiler OpenModelica v1.18.0 (64-bit). */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "Radiator_functions.h"

#ifdef __cplusplus
extern "C" {
#endif

#define Radiator_Radiator_Medium_ThermodynamicState__desc_added 1
const char* Radiator_Radiator_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description Radiator_Radiator_Medium_ThermodynamicState__desc = {
  "Radiator_Radiator_Medium_ThermodynamicState", /* package_record__X */
  "Radiator.Radiator.Medium.ThermodynamicState", /* package.record_X */
  Radiator_Radiator_Medium_ThermodynamicState__desc__fields
};

void Radiator_Radiator_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Radiator_Radiator_Medium_ThermodynamicState* ths = (Radiator_Radiator_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
// This function should eventualy replace the default 'modelica' record constructor funcition
// that omc used to generate, i.e., replace functionBodyRecordConstructor template.
/*
Radiator_Radiator_Medium_ThermodynamicState omc_Radiator_Radiator_Medium_ThermodynamicState(threadData_t *threadData , modelica_real  in_p, modelica_real  in_T) {
  Radiator_Radiator_Medium_ThermodynamicState dst;
  // TODO Improve me. No need to initalize the record members with defaults in Radiator_Radiator_Medium_ThermodynamicState_construct
  // We should just do the allocs here and then copy the input parameters as default values instead.
  Radiator_Radiator_Medium_ThermodynamicState_construct(threadData, dst);
  dst._p =  in_p;
  dst._T =  in_T;
  return dst;
}
*/

void Radiator_Radiator_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Radiator_Radiator_Medium_ThermodynamicState* src = (Radiator_Radiator_Medium_ThermodynamicState*)(v_src);
  Radiator_Radiator_Medium_ThermodynamicState* dst = (Radiator_Radiator_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}

#define Radiator_Radiator_res_Medium_ThermodynamicState__desc_added 1
const char* Radiator_Radiator_res_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description Radiator_Radiator_res_Medium_ThermodynamicState__desc = {
  "Radiator_Radiator_res_Medium_ThermodynamicState", /* package_record__X */
  "Radiator.Radiator.res.Medium.ThermodynamicState", /* package.record_X */
  Radiator_Radiator_res_Medium_ThermodynamicState__desc__fields
};

void Radiator_Radiator_res_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Radiator_Radiator_res_Medium_ThermodynamicState* ths = (Radiator_Radiator_res_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
// This function should eventualy replace the default 'modelica' record constructor funcition
// that omc used to generate, i.e., replace functionBodyRecordConstructor template.
/*
Radiator_Radiator_res_Medium_ThermodynamicState omc_Radiator_Radiator_res_Medium_ThermodynamicState(threadData_t *threadData , modelica_real  in_p, modelica_real  in_T) {
  Radiator_Radiator_res_Medium_ThermodynamicState dst;
  // TODO Improve me. No need to initalize the record members with defaults in Radiator_Radiator_res_Medium_ThermodynamicState_construct
  // We should just do the allocs here and then copy the input parameters as default values instead.
  Radiator_Radiator_res_Medium_ThermodynamicState_construct(threadData, dst);
  dst._p =  in_p;
  dst._T =  in_T;
  return dst;
}
*/

void Radiator_Radiator_res_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Radiator_Radiator_res_Medium_ThermodynamicState* src = (Radiator_Radiator_res_Medium_ThermodynamicState*)(v_src);
  Radiator_Radiator_res_Medium_ThermodynamicState* dst = (Radiator_Radiator_res_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}

#define Radiator_Radiator_vol_Medium_ThermodynamicState__desc_added 1
const char* Radiator_Radiator_vol_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description Radiator_Radiator_vol_Medium_ThermodynamicState__desc = {
  "Radiator_Radiator_vol_Medium_ThermodynamicState", /* package_record__X */
  "Radiator.Radiator.vol.Medium.ThermodynamicState", /* package.record_X */
  Radiator_Radiator_vol_Medium_ThermodynamicState__desc__fields
};

void Radiator_Radiator_vol_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Radiator_Radiator_vol_Medium_ThermodynamicState* ths = (Radiator_Radiator_vol_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
// This function should eventualy replace the default 'modelica' record constructor funcition
// that omc used to generate, i.e., replace functionBodyRecordConstructor template.
/*
Radiator_Radiator_vol_Medium_ThermodynamicState omc_Radiator_Radiator_vol_Medium_ThermodynamicState(threadData_t *threadData , modelica_real  in_p, modelica_real  in_T) {
  Radiator_Radiator_vol_Medium_ThermodynamicState dst;
  // TODO Improve me. No need to initalize the record members with defaults in Radiator_Radiator_vol_Medium_ThermodynamicState_construct
  // We should just do the allocs here and then copy the input parameters as default values instead.
  Radiator_Radiator_vol_Medium_ThermodynamicState_construct(threadData, dst);
  dst._p =  in_p;
  dst._T =  in_T;
  return dst;
}
*/

void Radiator_Radiator_vol_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Radiator_Radiator_vol_Medium_ThermodynamicState* src = (Radiator_Radiator_vol_Medium_ThermodynamicState*)(v_src);
  Radiator_Radiator_vol_Medium_ThermodynamicState* dst = (Radiator_Radiator_vol_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}

#define Radiator_Radiator_vol_dynBal_Medium_ThermodynamicState__desc_added 1
const char* Radiator_Radiator_vol_dynBal_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description Radiator_Radiator_vol_dynBal_Medium_ThermodynamicState__desc = {
  "Radiator_Radiator_vol_dynBal_Medium_ThermodynamicState", /* package_record__X */
  "Radiator.Radiator.vol.dynBal.Medium.ThermodynamicState", /* package.record_X */
  Radiator_Radiator_vol_dynBal_Medium_ThermodynamicState__desc__fields
};

void Radiator_Radiator_vol_dynBal_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Radiator_Radiator_vol_dynBal_Medium_ThermodynamicState* ths = (Radiator_Radiator_vol_dynBal_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
// This function should eventualy replace the default 'modelica' record constructor funcition
// that omc used to generate, i.e., replace functionBodyRecordConstructor template.
/*
Radiator_Radiator_vol_dynBal_Medium_ThermodynamicState omc_Radiator_Radiator_vol_dynBal_Medium_ThermodynamicState(threadData_t *threadData , modelica_real  in_p, modelica_real  in_T) {
  Radiator_Radiator_vol_dynBal_Medium_ThermodynamicState dst;
  // TODO Improve me. No need to initalize the record members with defaults in Radiator_Radiator_vol_dynBal_Medium_ThermodynamicState_construct
  // We should just do the allocs here and then copy the input parameters as default values instead.
  Radiator_Radiator_vol_dynBal_Medium_ThermodynamicState_construct(threadData, dst);
  dst._p =  in_p;
  dst._T =  in_T;
  return dst;
}
*/

void Radiator_Radiator_vol_dynBal_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Radiator_Radiator_vol_dynBal_Medium_ThermodynamicState* src = (Radiator_Radiator_vol_dynBal_Medium_ThermodynamicState*)(v_src);
  Radiator_Radiator_vol_dynBal_Medium_ThermodynamicState* dst = (Radiator_Radiator_vol_dynBal_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}

#define Radiator_flow__sink_Medium_ThermodynamicState__desc_added 1
const char* Radiator_flow__sink_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description Radiator_flow__sink_Medium_ThermodynamicState__desc = {
  "Radiator_flow__sink_Medium_ThermodynamicState", /* package_record__X */
  "Radiator.flow_sink.Medium.ThermodynamicState", /* package.record_X */
  Radiator_flow__sink_Medium_ThermodynamicState__desc__fields
};

void Radiator_flow__sink_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Radiator_flow__sink_Medium_ThermodynamicState* ths = (Radiator_flow__sink_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
// This function should eventualy replace the default 'modelica' record constructor funcition
// that omc used to generate, i.e., replace functionBodyRecordConstructor template.
/*
Radiator_flow__sink_Medium_ThermodynamicState omc_Radiator_flow__sink_Medium_ThermodynamicState(threadData_t *threadData , modelica_real  in_p, modelica_real  in_T) {
  Radiator_flow__sink_Medium_ThermodynamicState dst;
  // TODO Improve me. No need to initalize the record members with defaults in Radiator_flow__sink_Medium_ThermodynamicState_construct
  // We should just do the allocs here and then copy the input parameters as default values instead.
  Radiator_flow__sink_Medium_ThermodynamicState_construct(threadData, dst);
  dst._p =  in_p;
  dst._T =  in_T;
  return dst;
}
*/

void Radiator_flow__sink_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Radiator_flow__sink_Medium_ThermodynamicState* src = (Radiator_flow__sink_Medium_ThermodynamicState*)(v_src);
  Radiator_flow__sink_Medium_ThermodynamicState* dst = (Radiator_flow__sink_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}

#define Radiator_flow__source_Medium_ThermodynamicState__desc_added 1
const char* Radiator_flow__source_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description Radiator_flow__source_Medium_ThermodynamicState__desc = {
  "Radiator_flow__source_Medium_ThermodynamicState", /* package_record__X */
  "Radiator.flow_source.Medium.ThermodynamicState", /* package.record_X */
  Radiator_flow__source_Medium_ThermodynamicState__desc__fields
};

void Radiator_flow__source_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Radiator_flow__source_Medium_ThermodynamicState* ths = (Radiator_flow__source_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
// This function should eventualy replace the default 'modelica' record constructor funcition
// that omc used to generate, i.e., replace functionBodyRecordConstructor template.
/*
Radiator_flow__source_Medium_ThermodynamicState omc_Radiator_flow__source_Medium_ThermodynamicState(threadData_t *threadData , modelica_real  in_p, modelica_real  in_T) {
  Radiator_flow__source_Medium_ThermodynamicState dst;
  // TODO Improve me. No need to initalize the record members with defaults in Radiator_flow__source_Medium_ThermodynamicState_construct
  // We should just do the allocs here and then copy the input parameters as default values instead.
  Radiator_flow__source_Medium_ThermodynamicState_construct(threadData, dst);
  dst._p =  in_p;
  dst._T =  in_T;
  return dst;
}
*/

void Radiator_flow__source_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Radiator_flow__source_Medium_ThermodynamicState* src = (Radiator_flow__source_Medium_ThermodynamicState*)(v_src);
  Radiator_flow__source_Medium_ThermodynamicState* dst = (Radiator_flow__source_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}

#ifdef __cplusplus
}
#endif

